#!/bin/bash
cd ~/Developer/EC/assignmentfiles_2017
javac -cp contest.jar player13.java Genome.java
jar cmf MainClass.txt submission.jar player13.class Genome.class

# java -jar testrun.jar -submission=player13  -evaluation=SphereEvaluation -seed=0 #hasStructure and isSeparable
# java -jar testrun.jar -submission=player13  -evaluation=BentCigarFunction -seed=0
# java -jar testrun.jar -submission=player13  -evaluation=SchaffersEvaluation -seed=0 # isMultimodal and hasStructure
# java -jar testrun.jar -submission=player13  -evaluation=KatsuuraEvaluation -seed=0 #   isMultimodal


 #COUNTER=10
 #until [  $COUNTER -lt 1 ]; do
     #echo SEED $COUNTER
     #let COUNTER-=1
     #echo BentCigarFunction
     #java -jar testrun.jar -submission=player13  -evaluation=BentCigarFunction -seed=$COUNTER
     #echo SchaffersEvaluation
     #java -jar testrun.jar -submission=player13  -evaluation=SchaffersEvaluation -seed=$COUNTER # isMultimodal and hasStructure
     #echo KatsuuraEvaluation
     #java -jar testrun.jar -submission=player13  -evaluation=KatsuuraEvaluation -seed=$COUNTER #   isMultimodal
 #done






declare -a populationSize=(
"20" "30" "100" "300" "1000"
)
declare -a genome_mutation_chance=(
"1" "0.5" "0.1" "0.05" "0.01" "0.005" "0.001" "0.005" "0.001"
)
declare -a mutation_step=(
"1" "0.5" "0.1" "0.05" "0.01" "0.005" "0.001" "0.005" "0.001"
)
declare -a tournamentSelection_slice=(
"5" "10"
)
declare -a cooling_rate=(
"1" "0.5" "0.1" "0.05" "0.01" "0.005" "0.001" "0.005" "0.001" "0.0005" "0.0001"
)
declare -a cutoff=(
"4" "8"
)
declare -a race_limit=(
"1"
)

declare -a populationSize=(
"400" "800" "1000" "2000"
)
declare -a genome_mutation_chance=(
"1" "0.1" "0.01" "0.001"
)
declare -a mutation_step=(
"0.000000000001" "0.0000000000001" "0.00000000000001" "0.000000000000001" "0.0000000000000001"
)
declare -a tournamentSelection_slice=(
"40"
)
declare -a cooling_rate=(
"0.001" "0.0001" "0.00001"
)
declare -a cutoff=(
"40"
)
declare -a race_limit=(
"4" "5" "6"
)

# {1002} & {40, 8} & {0.1} & {0.01, 1, 1} & {$10^{-6}$} & {1} & {9.999999992} & {190}\\
# {10} & {10, 4} & {0.1} & {1, 1, 1} & {0.001} & {1} & {9.999999994} & {153}\\


declare -a populationSize=(
"300" "500" "1000" "2000"
)
declare -a genome_mutation_chance=(
"1" "0.1" "0.01"
)
declare -a mutation_step=(
"1" "0.1" "0.01" "0.001" "0.0001" "0.00001" "0.000001" "0.0000001" "0.00000001" "0.000000001" "0.0000000001" "0.00000000001" "0.000000000001" "0.0000000000001" "0.00000000000001" "0.000000000000001" "0.0000000000000001" "0.00000000000000001"
)
declare -a tournamentSelection_slice=(
"40"
)
declare -a cooling_rate=(
"0.000000000000000000001"
)
declare -a cutoff=(
"2"
)
declare -a race_limit=(
"1"
)

#300 , 1.0 , 1.0E-9 , 40 , 1.0E-15 , 4 , 1 , 0


for ps in "${populationSize[@]}"
do
    for mutchance in "${genome_mutation_chance[@]}"
    do
        for mutstep in "${mutation_step[@]}"
        do
            for slice in "${tournamentSelection_slice[@]}"
            do
                for coolrate in "${cooling_rate[@]}"
                do
                    for cut in "${cutoff[@]}"
                    do
                    echo "------------------------------------------------------------------------------------------------------"
                        for race in "${race_limit[@]}"
                        do
                            COUNTER=1
                            until [  $COUNTER -lt 1 ];
                            do
                                let COUNTER-=1
                                java -Dps=$ps -Dmutchance=$mutchance -Dmutstep=$mutstep -Dslice=$slice -Dcoolrate=$coolrate -Dcut=$cut -Drace=$race -jar testrun.jar -submission=player13  -evaluation=BentCigarFunction -seed=$COUNTER
                                #java -Dps=$ps -Dmutchance=$mutchance -Dmutstep=$mutstep -Dslice=$slice -Dcoolrate=$coolrate -Dcut=$cut -Drace=$race -jar testrun.jar -submission=player13  -evaluation=SchaffersEvaluation -seed=$COUNTER
                                #java -Dps=$ps -Dmutchance=$mutchance -Dmutstep=$mutstep -Dslice=$slice -Dcoolrate=$coolrate -Dcut=$cut -Drace=$race -jar testrun.jar -submission=player13  -evaluation=KatsuuraEvaluation -seed=$COUNTER
                            done
                        done
                    done
                done
            done
        done
    done

done