#!/bin/bash
cd ~/Developer/assignmentfiles_2017
javac -cp contest.jar player13.java
jar cmf MainClass.txt submission.jar player13.class
java -jar testrun.jar -submission=player13  -evaluation=SchaffersEvaluation -seed=1
